### ISSUE TITLE
パスワード変更画面から戻れない

### ISSUE THREAD

**Issue by tomoki-miso** [junjun-1345/aizuchi_app#130]
## 背景

-

## 工数（ストーリーポイント）

- 1,2,3,5,8,12,

## 受入条件

- [x] パスワード変更画面から戻れる

## 備考
![image](https://github.com/junjun-1345/aizuchi_app/assets/107928941/24e368ac-1e49-4dac-b4e6-2b494885aea2)

**Comment by junjun-1345** [comment]
確認
