### ISSUE TITLE
バージョン管理

### ISSUE THREAD

**Issue by tomoki-miso** [junjun-1345/aizuchi_app#88]
## 背景

大幅なアップデートや重大なバグが発見された際にユーザーが使うバージョンを管理する必要があるため。

## 工数（ストーリーポイント）

- 1,2,3,5,8,12,

## 受入条件

- [x] FireBase RemoteConfigの設定
- [x] アプリ起動時にアプリのバージョンをチェック
- [x] 規定のバージョン以下なら強制アップデート
- [x] （必要であれば）最新版がある場合はアップデート

## 備考
以下が参考になりそうです
https://qiita.com/sacred-sanctuary/items/9ca45ce39afe2fdb470f

面倒だったらFireStoreでも可能ではあります。（私はこの手法を使っています）
https://zenn.dev/flutteruniv_dev/articles/713dca4c5bf080

**Comment by junjun-1345** [comment]
完了

**Comment by junjun-1345** [comment]
- [ ] ダイアログ表示されないバグ

**Comment by junjun-1345** [comment]
lgtm
